(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const status=m=>{const e=$('#status');if(e)e.textContent=m};
const load=async(src,global)=>{if(global&&window[global])return window[global];await new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=()=>rej(Error('Could not load conversion library. Please check your internet connection and try again.'));document.head.appendChild(s)});return global?window[global]:true};
const bytesToMB=b=>(b/1048576).toFixed(2)+' MB';
const save=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2500)};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setupFiles(){const dz=$('.dropzone'),input=$('input[type=file]');if(!dz||!input)return;dz.onclick=e=>{if(e.target!==input)input.click()};['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{input.files=e.dataTransfer.files;input.dispatchEvent(new Event('change'))})}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;return await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs').then(m=>{m.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=m;return m})}
async function pdfLib(){return load('https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js','PDFLib')}
async function jsPDF(){return load('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','jspdf').then(x=>x.jsPDF)}
async function zip(){return load('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','JSZip')}
async function mammoth(){return load('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js','mammoth')}
async function pptxgen(){return load('https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.min.js','pptxgen')}
async function docxPreview(){return load('https://cdn.jsdelivr.net/npm/docx-preview@0.3.7/dist/docx-preview.min.js','docx')}
async function html2pdf(){return load('https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js','html2pdf')}
async function html2canvasLib(){return load('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js','html2canvas')}
async function docxBlob(paragraphs){const Z=await zip(),z=new Z();const body=paragraphs.map(p=>`<w:p>${p.pageBreak?'<w:r><w:br w:type="page"/></w:r>':''}<w:r><w:t xml:space="preserve">${esc(p.text||p)}</w:t></w:r></w:p>`).join('');const ct=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;const rel=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="900" w:right="900" w:bottom="900" w:left="900"/></w:sectPr></w:body></w:document>`;z.file('[Content_Types].xml',ct);z.file('_rels/.rels',rel);z.file('word/document.xml',doc);return z.generateAsync({type:'blob'})}
async function extractPdfText(file){const pdf=await (await pdfjs()).getDocument({data:await file.arrayBuffer()}).promise;const out=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent(),items=c.items.filter(x=>x.str&&x.str.trim());items.sort((a,b)=>{const ay=a.transform[5],by=b.transform[5];return Math.abs(by-ay)>3?by-ay:a.transform[4]-b.transform[4]});let lines=[];for(const it of items){const y=it.transform[5];let line=lines.find(x=>Math.abs(x.y-y)<3);if(!line){line={y,text:''};lines.push(line)}line.text+=(line.text?' ':'')+it.str.trim()}out.push(...lines.sort((a,b)=>b.y-a.y).map((x,j)=>({text:x.text,pageBreak:i>1&&j===0})));}return out}
async function extractPptText(file){const Z=await zip(),z=await Z.loadAsync(await file.arrayBuffer()),names=Object.keys(z.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));const out=[];for(const n of names){const xml=await z.file(n).async('string');const vals=[...xml.matchAll(/<a:t[^>]*>([\s\S]*?)<\/a:t>/g)].map(m=>m[1].replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'));out.push({text:vals.join(' ')});out.push({text:'',pageBreak:true})}if(out.length)out.pop();return out}
function imageLoad(file){return new Promise((res,rej)=>{const img=new Image();const u=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(u);res(img)};img.onerror=()=>{URL.revokeObjectURL(u);rej(Error('Could not read '+file.name))};img.src=u})}
async function canvasImage(file,maxW=2400,quality=.9,format='image/jpeg'){const img=await imageLoad(file),s=Math.min(1,maxW/img.width),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*s));c.height=Math.max(1,Math.round(img.height*s));c.getContext('2d').drawImage(img,0,0,c.width,c.height);return await new Promise(r=>c.toBlob(r,format,quality))}
async function imagePdf(files){const J=await jsPDF(),size=$('#pageSize')?.value||'a4',orientation=$('#orientation')?.value||'auto',margin=Number($('#margin')?.value??10);const first=await imageLoad(files[0]);let firstOrient=orientation==='auto'?(first.width>=first.height?'landscape':'portrait'):orientation;const doc=new J({unit:'mm',format:size,orientation:firstOrient});for(let i=0;i<files.length;i++){const img=i===0?first:await imageLoad(files[i]);let orient=orientation==='auto'?(img.width>=img.height?'landscape':'portrait'):orientation;if(i>0)doc.addPage(size,orient);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const maxW=pw-2*margin,maxH=ph-2*margin;const iw=img.width/3.7795275591,ih=img.height/3.7795275591,scale=Math.min(maxW/iw,maxH/ih);const w=iw*scale,h=ih*scale;doc.addImage(img,'JPEG',(pw-w)/2,(ph-h)/2,w,h,undefined,'FAST')}return doc.output('blob')}
async function blobZip(entries,name){const Z=await zip(),z=new Z();for(const [n,b] of entries)z.file(n,b);return z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}).then(b=>save(b,name))}
async function pdfPages(file,format,scale=2){const lib=await pdfjs(),pdf=await lib.getDocument({data:await file.arrayBuffer()}).promise,arr=[];for(let i=1;i<=pdf.numPages;i++){status(`Rendering page ${i} of ${pdf.numPages}…`);const p=await pdf.getPage(i),v=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const mime=format==='png'?'image/png':'image/jpeg';arr.push([`page-${i}.${format}`,await new Promise(r=>c.toBlob(r,mime,.94))])}return arr}
function bind(){setupFiles();const type=document.body.dataset.tool;if(!type)return;const input=$('input[type=file]');if(input)input.addEventListener('change',()=>{$('#fileNames').textContent=[...input.files].map(f=>f.name+' ('+bytesToMB(f.size)+')').join('\n');const n=$('#fileCount');if(n)n.textContent=`${input.files.length} file${input.files.length===1?'':'s'} selected`;});const go=$('#run');if(!go)return;go.addEventListener('click',async()=>{try{go.disabled=true;status('Working…');const files=[...input.files];if(!files.length)throw Error('Please choose at least one file.');
if(type==='jpg-pdf'||type==='images-pdf'){save(await imagePdf(files),type+'.pdf');status('Done. Your PDF is ready to download.');}
else if(type==='image-compressor'){const target=Number($('#target').value)*1024,maxW=Number($('#maxWidth').value)||2400,fmt=$('#format')?.value||'jpg',mime=fmt==='webp'?'image/webp':'image/jpeg',ext=fmt==='webp'?'webp':'jpg',results=[];for(let n=0;n<files.length;n++){let q=.9,b=null;for(let i=0;i<14;i++){b=await canvasImage(files[n],maxW,q,mime);if(b.size<=target||q<=.2)break;q-=.05}results.push([files[n].name.replace(/\.[^.]+$/,'')+'.'+ext,b])}if(results.length===1)save(results[0][1],results[0][0]);else await blobZip(results,'compressed-images.zip');status(`Done. ${results.length} image${results.length===1?'':'s'} compressed.`);}
else if(type==='image-resizer'){const w=Number($('#width').value),h=Number($('#height').value);if(!w||!h)throw Error('Enter valid width and height.');const results=[];for(const f of files){const img=await imageLoad(f);let nw=w,nh=h;if($('#keep')?.checked){const s=Math.min(w/img.width,h/img.height);nw=Math.max(1,Math.round(img.width*s));nh=Math.max(1,Math.round(img.height*s))}const c=document.createElement('canvas');c.width=nw;c.height=nh;c.getContext('2d').drawImage(img,0,0,nw,nh);const b=await new Promise(r=>c.toBlob(r,'image/jpeg',.92));results.push([f.name.replace(/\.[^.]+$/,'')+'-resized.jpg',b])}if(results.length===1)save(results[0][1],results[0][0]);else await blobZip(results,'resized-images.zip');status(`Done. ${results.length} image${results.length===1?'':'s'} resized.`);}
else if(type==='pdf-jpg'||type==='pdf-png'){const format=type==='pdf-png'?'png':'jpg',scale=Number($('#quality')?.value||2),entries=await pdfPages(files[0],format,scale);if(entries.length===1)save(entries[0][1],files[0].name.replace(/\.[^.]+$/,'')+'-page-1.'+format);else await blobZip(entries,files[0].name.replace(/\.[^.]+$/,'')+'-'+format+'-pages.zip');status(`Done. Exported ${entries.length} page${entries.length===1?'':'s'} as ${format.toUpperCase()}.`);}
else if(type==='merge-pdf'){const L=await pdfLib(),out=await L.PDFDocument.create();for(const f of files){status(`Adding ${f.name}…`);const src=await L.PDFDocument.load(await f.arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}save(new Blob([await out.save({useObjectStreams:true})],{type:'application/pdf'}),'merged.pdf');status(`Done. Merged ${files.length} PDF files in the selected order.`);}
else if(type==='compress-pdf'){const lib=await pdfjs(),J=await jsPDF(),target=Number($('#target').value)*1024,level=$('#compression')?.value||'recommended';let quality=level==='extreme'?.45:level==='high'?.62:.76,scale=level==='extreme'?1.1:level==='high'?1.45:1.8,result;const pdf=await lib.getDocument({data:await files[0].arrayBuffer()}).promise;for(let attempt=0;attempt<4;attempt++){const first=await pdf.getPage(1),vp=first.getViewport({scale:1});const doc=new J({unit:'pt',format:[vp.width,vp.height],compress:true});for(let i=1;i<=pdf.numPages;i++){if(i>1){const pg=await pdf.getPage(i),v=pg.getViewport({scale:1});doc.addPage([v.width,v.height])}const pg=await pdf.getPage(i),v=pg.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await pg.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const b=await new Promise(r=>c.toBlob(r,'image/jpeg',quality));const u=URL.createObjectURL(b),img=new Image();await new Promise((r,j)=>{img.onload=r;img.onerror=j;img.src=u});const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();doc.addImage(img,'JPEG',0,0,pw,ph,undefined,'FAST');URL.revokeObjectURL(u)}result=doc.output('blob');if(result.size<=target||level!=='target')break;quality-=.08;scale-=.15}save(result,files[0].name.replace(/\.[^.]+$/,'')+'-compressed.pdf');status(`Done. ${bytesToMB(files[0].size)} → ${bytesToMB(result.size)}.`);}
else if(type==='pdf-word'){const p=await extractPdfText(files[0]);save(await docxBlob(p),'pdf-to-word.docx');status(`Done. Created an editable Word document from ${p.length} extracted text lines. Text-heavy PDFs work best; complex graphics may not reproduce exactly.`);}
else if(type==='ppt-word'){const p=await extractPptText(files[0]);save(await docxBlob(p),'ppt-to-word.docx');status('Done. Created an editable Word document from the presentation text. Slide graphics and advanced positioning may not reproduce exactly.');}
else if(type==='word-ppt'){const renderBox=document.getElementById('docxRender');if(!renderBox)throw Error('Preview area is missing. Please refresh the page.');renderBox.innerHTML='';renderBox.style.display='block';status('Rendering the Word document for PowerPoint…');const D=await docxPreview();await D.renderAsync(await files[0].arrayBuffer(),renderBox,null,{className:'docx',inWrapper:true,ignoreWidth:false,ignoreHeight:false,breakPages:true});const C=await html2canvasLib();const P=await pptxgen();const ppt=new P();ppt.layout='LAYOUT_WIDE';const pages=[...renderBox.querySelectorAll('.docx-wrapper > section, .docx-wrapper > div')].filter(e=>e.offsetWidth&&e.offsetHeight);const pageEls=pages.length?pages:[renderBox];for(let i=0;i<pageEls.length;i++){status(`Creating slide ${i+1} of ${pageEls.length}…`);const canvas=await window.html2canvas(pageEls[i],{scale:2,useCORS:true,backgroundColor:'#ffffff'});const slide=ppt.addSlide();slide.background={color:'FFFFFF'};slide.addImage({data:canvas.toDataURL('image/png'),x:0,y:0,w:13.333,h:7.5})}await ppt.writeFile({fileName:'word-to-ppt.pptx'});status(`Done. Created ${pageEls.length} PowerPoint slide${pageEls.length===1?'':'s'} from the rendered Word pages.`);}
else if(type==='word-pdf'){const renderBox=document.getElementById('docxRender');if(!renderBox)throw Error('Preview area is missing. Please refresh the page.');renderBox.innerHTML='';renderBox.style.display='block';status('Rendering Word layout, tables, images and formatting…');const D=await docxPreview();await D.renderAsync(await files[0].arrayBuffer(),renderBox,null,{className:'docx',inWrapper:true,ignoreWidth:false,ignoreHeight:false,breakPages:true,experimental:false});const H=await html2pdf();status('Creating PDF from the rendered document…');const opt={margin:0,filename:'word-to-pdf.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff',logging:false},jsPDF:{unit:'pt',format:'a4',orientation:'portrait',compress:true},pagebreak:{mode:['css','legacy']}};await H().set(opt).from(renderBox).save();status('Done. The PDF was created from the rendered Word layout.');}
}catch(e){console.error(e);status('Could not complete the conversion. '+(e.message||e));}finally{go.disabled=false}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
