(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const status=m=>{const e=$('#status');if(e)e.textContent=m};
const load=async(src,global)=>{if(global&&window[global])return window[global];return await new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>res(global?window[global]:true);s.onerror=()=>rej(new Error('Could not load the required conversion library. Please check your internet connection and try again.'));document.head.appendChild(s)})};
const bytes=b=>{if(!Number.isFinite(b))return '0 B';if(b<1024)return `${b} B`;if(b<1048576)return `${(b/1024).toFixed(1)} KB`;return `${(b/1048576).toFixed(2)} MB`};
const save=(blob,name)=>{if(!blob)throw new Error('The conversion returned no file.');const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)};
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function setupFiles(){const dz=$('.dropzone'),input=$('input[type=file]');if(!dz||!input)return;dz.addEventListener('click',e=>{if(e.target!==input)input.click()});['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();e.stopPropagation();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();e.stopPropagation();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{const dt=e.dataTransfer;if(dt?.files?.length){input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))}})}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;const m=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');m.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=m;return m}
async function pdfLib(){return load('https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js','PDFLib')}
async function jsPDF(){const m=await load('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','jspdf');return m.jsPDF}
async function zip(){return load('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','JSZip')}
async function docxPreview(){await zip();return load('https://cdn.jsdelivr.net/npm/docx-preview@0.4.1/dist/docx-preview.min.js','docx')}
async function pptxgen(){return load('https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.min.js','pptxgen')}
async function qpdf(){if(window.__usrQpdf)return window.__usrQpdf;const mod=await import('https://cdn.jsdelivr.net/npm/qpdf-wasm-esm-embedded@1.1.1/qpdf.mjs');const factory=mod.default||mod.QPDF||mod;window.__usrQpdf=await factory();return window.__usrQpdf}
function imageLoad(file){return new Promise((res,rej)=>{const img=new Image();const u=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(u);res(img)};img.onerror=()=>{URL.revokeObjectURL(u);rej(new Error(`Could not read ${file.name}.`))};img.src=u})}
async function imageData(file,maxW=10000,quality=.98){const img=await imageLoad(file);const scale=Math.min(1,maxW/img.naturalWidth);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d',{alpha:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,c.width,c.height);const png=c.toDataURL('image/png');const jpg=c.toDataURL('image/jpeg',quality);return {img,c,png,jpg}}
function mimeFor(file){return /^image\/png$/i.test(file.type)?'PNG':'JPEG'}
async function imagePdf(files){const J=await jsPDF();const size=$('#pageSize')?.value||'a4',orientation=$('#orientation')?.value||'auto',margin=Number($('#margin')?.value??10);let doc=null;for(let i=0;i<files.length;i++){status(`Adding image ${i+1} of ${files.length}…`);const {img,png,jpg}=await imageData(files[i]);let orient=orientation==='auto'?(img.naturalWidth>=img.naturalHeight?'landscape':'portrait'):orientation;if(i===0)doc=new J({unit:'mm',format:size,orientation:orient,compress:true});else doc.addPage(size,orient);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight(),maxW=pw-2*margin,maxH=ph-2*margin;const iw=img.naturalWidth*25.4/96,ih=img.naturalHeight*25.4/96;const scale=Math.min(maxW/iw,maxH/ih);const w=iw*scale,h=ih*scale;const data=mimeFor(files[i])==='PNG'?png:jpg;doc.addImage(data,mimeFor(files[i]),(pw-w)/2,(ph-h)/2,w,h,undefined,'FAST');}return doc.output('blob')}
async function blobZip(entries,name){const Z=await zip(),z=new Z();for(const [n,b] of entries)z.file(n,b);save(await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),name)}
async function pdfPages(file,format,scale){const lib=await pdfjs(),pdf=await lib.getDocument({data:await file.arrayBuffer(),isEvalSupported:true}).promise,arr=[];for(let i=1;i<=pdf.numPages;i++){status(`Rendering page ${i} of ${pdf.numPages} at high quality…`);const p=await pdf.getPage(i),v=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);const ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;await p.render({canvasContext:ctx,viewport:v,background:'white'}).promise;const mime=format==='png'?'image/png':'image/jpeg';const blob=await new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Could not create the image output.')),mime,format==='jpg'?.97:undefined));arr.push([`page-${i}.${format}`,blob]);}return arr}
function docxImageXml(id,name,cx,cy){return `<w:p><w:pPr><w:spacing w:before="0" w:after="0"/></w:pPr><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><wp:extent cx="${cx}" cy="${cy}"/><wp:docPr id="${id}" name="${esc(name)}"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="0" name="${esc(name)}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rId${id}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`}
async function imagePagesToDocx(pages){const Z=await zip(),z=new Z();const rels=[],parts=[],body=[];const pageRels=[];for(let i=0;i<pages.length;i++){const [name,blob,ptW,ptH]=pages[i];const id=i+1,media=`word/media/page-${id}.png`;z.file(media,blob);rels.push(`<Relationship Id="rId${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/page-${id}.png"/>`);const cx=Math.round(ptW/72*914400),cy=Math.round(ptH/72*914400);body.push(docxImageXml(id,name,cx,cy));const twW=Math.round(ptW*20),twH=Math.round(ptH*20);body.push(`<w:p><w:pPr><w:sectPr><w:pgSz w:w="${twW}" w:h="${twH}"/><w:pgMar w:top="0" w:right="0" w:bottom="0" w:left="0"/></w:sectPr></w:pPr></w:p>`);}
const types=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;
const root=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;
const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body.join('')}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="0" w:right="0" w:bottom="0" w:left="0"/></w:sectPr></w:body></w:document>`;
const docRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels.join('')}</Relationships>`;
z.file('[Content_Types].xml',types);z.file('_rels/.rels',root);z.file('word/document.xml',doc);z.file('word/_rels/document.xml.rels',docRels);return z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}})}
async function pdfToExactWord(file){const lib=await pdfjs(),pdf=await lib.getDocument({data:await file.arrayBuffer()}).promise,pages=[];for(let i=1;i<=pdf.numPages;i++){status(`Preparing PDF page ${i} for high-fidelity Word…`);const p=await pdf.getPage(i),v=p.getViewport({scale:2.5}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v,background:'white'}).promise;const blob=await new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error('Could not render PDF page.')),'image/png'));const ptW=p.getViewport({scale:1}).width,ptH=p.getViewport({scale:1}).height;pages.push([`PDF page ${i}`,blob,ptW,ptH])}return imagePagesToDocx(pages)}
async function extractPdfText(file){const pdf=await (await pdfjs()).getDocument({data:await file.arrayBuffer()}).promise;const out=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent(),items=c.items.filter(x=>x.str&&x.str.trim());items.sort((a,b)=>{const ay=a.transform[5],by=b.transform[5];return Math.abs(by-ay)>3?by-ay:a.transform[4]-b.transform[4]});let lines=[];for(const it of items){const y=it.transform[5];let line=lines.find(x=>Math.abs(x.y-y)<3);if(!line){line={y,text:''};lines.push(line)}line.text+=(line.text?' ':'')+it.str.trim()}out.push(...lines.sort((a,b)=>b.y-a.y).map((x,j)=>({text:x.text,pageBreak:i>1&&j===0})));}return out}
async function extractPptText(file){const Z=await zip(),z=await Z.loadAsync(await file.arrayBuffer()),names=Object.keys(z.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));const out=[];for(const n of names){const xml=await z.file(n).async('string');const vals=[...xml.matchAll(/<a:t[^>]*>([\s\S]*?)<\/a:t>/g)].map(m=>m[1].replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>'));out.push({text:vals.join(' '),pageBreak:true})}if(out.length)out[out.length-1].pageBreak=false;return out}
async function textDocx(paragraphs){const Z=await zip(),z=new Z();const body=paragraphs.map(p=>`<w:p>${p.pageBreak?'<w:r><w:br w:type="page"/></w:r>':''}<w:r><w:t xml:space="preserve">${esc(p.text||p)}</w:t></w:r></w:p>`).join('');const ct=`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;const rel=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;const doc=`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="900" w:right="900" w:bottom="900" w:left="900"/></w:sectPr></w:body></w:document>`;z.file('[Content_Types].xml',ct);z.file('_rels/.rels',rel);z.file('word/document.xml',doc);return z.generateAsync({type:'blob'})}
async function renderWordPages(file){const box=$('#docxRender');if(!box)throw new Error('Preview area is missing. Please refresh the page.');box.innerHTML='';box.style.display='block';const D=await docxPreview();await D.renderAsync(await file.arrayBuffer(),box,null,{className:'docx',inWrapper:true,ignoreWidth:false,ignoreHeight:false,breakPages:true,ignoreLastRenderedPageBreak:false,renderHeaders:true,renderFooters:true,renderFootnotes:true,renderEndnotes:true,useBase64URL:true});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const pages=[...box.querySelectorAll('section.docx, .docx-wrapper > section, .docx-wrapper > div.docx')].filter(e=>e.offsetWidth>0&&e.offsetHeight>0);return pages.length?pages:[box]}
async function wordToPdf(file){const pages=await renderWordPages(file);const J=await jsPDF();let doc=null;const C=await load('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js','html2canvas');for(let i=0;i<pages.length;i++){status(`Creating high-fidelity PDF page ${i+1} of ${pages.length}…`);const el=pages[i];const rect=el.getBoundingClientRect();const scale=Math.min(3,Math.max(2,window.devicePixelRatio||2));const canvas=await C(el,{scale,useCORS:true,backgroundColor:'#ffffff',logging:false,foreignObjectRendering:false,removeContainer:true});const wPt=rect.width*72/96,hPt=rect.height*72/96;const orient=wPt>=hPt?'landscape':'portrait';if(i===0)doc=new J({unit:'pt',format:[wPt,hPt],orientation:orient,compress:true});else doc.addPage([wPt,hPt],orient);doc.addImage(canvas.toDataURL('image/jpeg',.98),'JPEG',0,0,wPt,hPt,undefined,'FAST')}return doc.output('blob')}
async function wordToPpt(file){const pages=await renderWordPages(file),P=await pptxgen(),ppt=new P();ppt.layout='LAYOUT_WIDE';const C=await load('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js','html2canvas');for(let i=0;i<pages.length;i++){status(`Creating PowerPoint slide ${i+1} of ${pages.length}…`);const canvas=await C(pages[i],{scale:2,useCORS:true,backgroundColor:'#fff',logging:false,foreignObjectRendering:false,removeContainer:true});const slide=ppt.addSlide();slide.background={color:'FFFFFF'};slide.addImage({data:canvas.toDataURL('image/png'),x:0,y:0,w:13.333,h:7.5})}const blob=await ppt.write({outputType:'blob',compression:true});return blob}
async function compressPdf(file,level,targetKB){if(!/^%PDF-/.test(await file.slice(0,5).text()))throw new Error('The selected file does not appear to be a valid PDF.');status('Loading the PDF optimization engine…');const q=await qpdf();const input=new Uint8Array(await file.arrayBuffer());const inPath='/usr/input.pdf',outPath='/usr/output.pdf';try{q.FS.writeFile(inPath,input)}catch{try{q.FS.mkdir('/usr')}catch{}q.FS.writeFile(inPath,input)}const jpegQuality=level==='extreme'?55:level==='high'?70:85;const args=['--object-streams=generate','--stream-data=compress','--recompress-flate','--compression-level=9','--optimize-images',`--jpeg-quality=${jpegQuality}`,'--linearize',inPath,outPath];status('Optimizing PDF streams, fonts and embedded objects…');await new Promise(r=>setTimeout(r,40));q.callMain(args);const out=q.FS.readFile(outPath);const blob=new Blob([out],{type:'application/pdf'});try{q.FS.unlink(inPath);q.FS.unlink(outPath)}catch{}if(blob.size>=file.size){status(`The original PDF is already at least as efficient as the optimizer could make it (${bytes(file.size)}). The original will be downloaded instead of a larger file.`);return file}if(targetKB&&blob.size>targetKB*1024){status(`Optimized PDF is ${bytes(blob.size)}. The requested ${targetKB} KB target cannot be reached without aggressive rasterization; a larger-but-readable PDF is not being falsely labelled as “under target”.`)}else status(`Compressed successfully: ${bytes(file.size)} → ${bytes(blob.size)}.`);return blob}
function bind(){setupFiles();const type=document.body.dataset.tool;if(!type)return;const input=$('input[type=file]');if(input)input.addEventListener('change',()=>{$('#fileNames').textContent=[...input.files].map(f=>`${f.name} (${bytes(f.size)})`).join('\n');const n=$('#fileCount');if(n)n.textContent=`${input.files.length} file${input.files.length===1?'':'s'} selected`});const go=$('#run');if(!go)return;go.addEventListener('click',async()=>{try{go.disabled=true;status('Working…');const files=[...input.files];if(!files.length)throw new Error('Please choose at least one file.');
if(type==='jpg-pdf'||type==='images-pdf'){save(await imagePdf(files),type==='jpg-pdf'?'jpg-to-pdf.pdf':'images-to-pdf.pdf');status('Done. The PDF was created without degrading the source image more than necessary.');}
else if(type==='image-compressor'){const target=Number($('#target')?.value||0)*1024,maxW=Number($('#maxWidth')?.value)||10000,fmt=$('#format')?.value||'jpg',mime=fmt==='webp'?'image/webp':'image/jpeg',ext=fmt==='webp'?'webp':'jpg',results=[];for(const f of files){const img=await imageLoad(f);const scale=Math.min(1,maxW/img.naturalWidth);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);let q=.94,b=null;for(let i=0;i<18;i++){b=await new Promise(r=>c.toBlob(r,mime,q));if(!target||b.size<=target||q<=.25)break;q-=.04}results.push([f.name.replace(/\.[^.]+$/,'')+'.'+ext,b])}if(results.length===1)save(results[0][1],results[0][0]);else await blobZip(results,'compressed-images.zip');status(`Done. ${results.length} image${results.length===1?'':'s'} compressed.`);}
else if(type==='image-resizer'){const w=Number($('#width')?.value),h=Number($('#height')?.value);if(!w||!h||w<1||h<1)throw new Error('Enter valid width and height.');const results=[];for(const f of files){const img=await imageLoad(f);let nw=w,nh=h;if($('#keep')?.checked){const s=Math.min(w/img.naturalWidth,h/img.naturalHeight);nw=Math.max(1,Math.round(img.naturalWidth*s));nh=Math.max(1,Math.round(img.naturalHeight*s))}const c=document.createElement('canvas');c.width=nw;c.height=nh;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,nw,nh);const mime=f.type==='image/png'?'image/png':'image/jpeg',ext=mime==='image/png'?'png':'jpg',b=await new Promise(r=>c.toBlob(r,mime,.96));results.push([f.name.replace(/\.[^.]+$/,'')+'-resized.'+ext,b])}if(results.length===1)save(results[0][1],results[0][0]);else await blobZip(results,'resized-images.zip');status(`Done. ${results.length} image${results.length===1?'':'s'} resized with high-quality interpolation.`);}
else if(type==='pdf-jpg'||type==='pdf-png'){const format=type==='pdf-png'?'png':'jpg',scale=Number($('#quality')?.value||3),entries=await pdfPages(files[0],format,scale);if(entries.length===1)save(entries[0][1],files[0].name.replace(/\.[^.]+$/,'')+'-page-1.'+format);else await blobZip(entries,files[0].name.replace(/\.[^.]+$/,'')+'-'+format+'-pages.zip');status(`Done. Exported ${entries.length} high-resolution page${entries.length===1?'':'s'} as ${format.toUpperCase()}.`);}
else if(type==='merge-pdf'){const L=await pdfLib(),out=await L.PDFDocument.create();for(const f of files){status(`Adding ${f.name}…`);const src=await L.PDFDocument.load(await f.arrayBuffer(),{ignoreEncryption:false});const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}save(new Blob([await out.save({useObjectStreams:true,addDefaultPage:false})],{type:'application/pdf'}),'merged.pdf');status(`Done. Merged ${files.length} PDF files while preserving their page content.`);}
else if(type==='compress-pdf'){const target=Number($('#target')?.value||0);const result=await compressPdf(files[0],$('#compression')?.value||'recommended',target);save(result,files[0].name.replace(/\.[^.]+$/,'')+'-compressed.pdf');}
else if(type==='pdf-word'){const mode=$('#conversionMode')?.value||'exact';if(mode==='editable'){const p=await extractPdfText(files[0]);save(await textDocx(p),'pdf-to-word-editable.docx');status('Done. Editable text mode created. For exact visual fidelity, choose Exact layout mode.')}else{save(await pdfToExactWord(files[0]),'pdf-to-word-high-fidelity.docx');status('Done. High-fidelity Word file created with each PDF page preserved at its original page size.');}}
else if(type==='ppt-word'){const p=await extractPptText(files[0]);save(await textDocx(p),'ppt-to-word.docx');status('Done. Slide text and page breaks were preserved. Complex slide graphics are not converted into editable Word objects.');}
else if(type==='word-pdf'){save(await wordToPdf(files[0]),'word-to-pdf-high-fidelity.pdf');status('Done. Word pages were rendered individually to preserve page size, tables, images, headers and footers as closely as the browser renderer permits.');}
else if(type==='word-ppt'){save(await wordToPpt(files[0]),'word-to-ppt-high-fidelity.pptx');status('Done. Each rendered Word page is preserved as a high-resolution PowerPoint slide.');}
else throw new Error('This tool is not configured correctly.');
}catch(e){console.error(e);status('Could not complete the conversion. '+(e?.message||String(e)))}finally{go.disabled=false}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();