(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const status=m=>{const e=$('#status');if(e)e.textContent=m};
const load=async(src,global)=>{if(global&&window[global])return window[global];await new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=()=>rej(Error('Could not load the conversion library. Please check your internet connection and try again.'));document.head.appendChild(s)});return global?window[global]:true};
const bytesToMB=b=>(b/1048576).toFixed(2)+' MB';
const save=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setupFiles(){const dz=$('.dropzone'),input=$('input[type=file]');if(!dz||!input)return;dz.onclick=e=>{if(e.target!==input)input.click()};['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{input.files=e.dataTransfer.files;input.dispatchEvent(new Event('change'))})}
async function pdfjs(){if(window.pdfjsLib)return window.pdfjsLib;return await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs').then(m=>{m.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';window.pdfjsLib=m;return m})}
async function pdfLib(){return load('https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js','PDFLib')}
async function jsPDF(){return load('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','jspdf').then(x=>x.jsPDF)}
async function zip(){return load('https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js','JSZip')}
async function docxPreview(){await zip();return load('https://cdn.jsdelivr.net/npm/docx-preview@0.4.1/dist/docx-preview.min.js','docx')}
async function html2canvasLib(){return load('https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js','html2canvas')}
async function pptxGen(){await zip();return load('https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js','PptxGenJS')}
async function pptxPreview(){return await import('https://esm.sh/pptx-preview@1.0.7').then(m=>m.default||m)}
async function qpdfOptimize(bytes,level){
  try{
    const mod=await import('https://cdn.jsdelivr.net/npm/qpdf-wasm-esm-embedded@1.1.1/qpdf.mjs');
    const factory=mod.default||mod.QPDF||mod;
    const q=await factory({noInitialRun:true});
    if(!q||!q.FS||!q.callMain)throw Error('QPDF runtime is unavailable');
    const input='/usr-input.pdf',output='/usr-output.pdf';
    q.FS.writeFile(input,new Uint8Array(bytes));
    const args=['--object-streams=generate','--compress-streams=y','--recompress-flate','--stream-data=compress'];
    if(level==='high'||level==='maximum')args.push('--optimize-images','--jpeg-quality='+(level==='maximum'?65:78));
    const rc=q.callMain([input,...args,output]);
    if(typeof rc==='number'&&rc!==0)throw Error('QPDF returned an error');
    const out=q.FS.readFile(output);
    return new Blob([out],{type:'application/pdf'});
  }catch(e){console.warn('QPDF optimization unavailable; using safe PDF optimization fallback.',e);return null}
}
async function safePdfOptimize(bytes){
  const L=await pdfLib();
  const src=await L.PDFDocument.load(bytes,{ignoreEncryption:false,updateMetadata:false});
  const out=await src.save({useObjectStreams:true,addDefaultPage:false,objectsPerTick:20,updateFieldAppearances:false});
  return new Blob([out],{type:'application/pdf'});
}
async function canvasImage(file,maxW=2400,quality=.9,format='image/jpeg'){const img=await imageLoad(file),s=Math.min(1,maxW/img.width),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*s));c.height=Math.max(1,Math.round(img.height*s));const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,c.width,c.height);return await new Promise(r=>c.toBlob(r,format,quality))}
function imageLoad(file){return new Promise((res,rej)=>{const img=new Image();const u=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(u);res(img)};img.onerror=()=>{URL.revokeObjectURL(u);rej(Error('Could not read '+file.name))};img.src=u})}
async function imagePdf(files){const J=await jsPDF(),size=$('#pageSize')?.value||'a4',orientation=$('#orientation')?.value||'auto',margin=Number($('#margin')?.value??10);const first=await imageLoad(files[0]);let firstOrient=orientation==='auto'?(first.width>=first.height?'landscape':'portrait'):orientation;const doc=new J({unit:'mm',format:size,orientation:firstOrient});for(let i=0;i<files.length;i++){const img=i===0?first:await imageLoad(files[i]);let orient=orientation==='auto'?(img.width>=img.height?'landscape':'portrait'):orientation;if(i>0)doc.addPage(size,orient);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight(),maxW=pw-2*margin,maxH=ph-2*margin,iw=img.width/3.7795275591,ih=img.height/3.7795275591,scale=Math.min(maxW/iw,maxH/ih),w=iw*scale,h=ih*scale;doc.addImage(img,'JPEG',(pw-w)/2,(ph-h)/2,w,h,undefined,'NONE')}return doc.output('blob')}
async function blobZip(entries,name){const Z=await zip(),z=new Z();for(const [n,b] of entries)z.file(n,b);return z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}).then(b=>save(b,name))}
async function pdfPages(file,format,scale=2){const lib=await pdfjs(),pdf=await lib.getDocument({data:await file.arrayBuffer()}).promise,arr=[];for(let i=1;i<=pdf.numPages;i++){status(`Rendering page ${i} of ${pdf.numPages}…`);const p=await pdf.getPage(i),v=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(v.width);c.height=Math.ceil(v.height);await p.render({canvasContext:c.getContext('2d',{alpha:false}),viewport:v}).promise;const mime=format==='png'?'image/png':'image/jpeg';arr.push([`page-${i}.${format}`,await new Promise(r=>c.toBlob(r,mime,format==='png'?1:.96))])}return arr}
async function extractPdfText(file){const pdf=await (await pdfjs()).getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent(),items=c.items.filter(x=>x.str&&x.str.trim());items.sort((a,b)=>{const ay=a.transform[5],by=b.transform[5];return Math.abs(by-ay)>3?by-ay:a.transform[4]-b.transform[4]});const lines=[];for(const it of items){const y=it.transform[5];let line=lines.find(x=>Math.abs(x.y-y)<3);if(!line){line={y,text:''};lines.push(line)}line.text+=(line.text?' ':'')+it.str.trim()}pages.push(lines.sort((a,b)=>b.y-a.y).map(x=>x.text));}return pages}
async function docxBlobPages(pages){const Z=await zip(),z=new Z();const paragraphs=[];pages.forEach((page,pi)=>{page.forEach(t=>paragraphs.push(`<w:p><w:r><w:t xml:space="preserve">${esc(t)}</w:t></w:r></w:p>`));if(pi<pages.length-1)paragraphs.push('<w:p><w:r><w:br w:type="page"/></w:r></w:p>')});const body=paragraphs.join('');const ct=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;const rel=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;const doc=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr></w:body></w:document>`;z.file('[Content_Types].xml',ct);z.file('_rels/.rels',rel);z.file('word/document.xml',doc);return z.generateAsync({type:'blob'})}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
async function renderDocxPages(file,box){box.innerHTML='';box.style.display='block';const D=await docxPreview();await D.renderAsync(await file.arrayBuffer(),box,null,{className:'docx',inWrapper:true,ignoreWidth:false,ignoreHeight:false,breakPages:true,experimental:false});await wait(150);let pages=[...box.querySelectorAll('.docx-wrapper > section')].filter(e=>e.offsetWidth&&e.offsetHeight);if(!pages.length)pages=[...box.querySelectorAll('.docx')].filter(e=>e.offsetWidth&&e.offsetHeight);if(!pages.length)pages=[box];return pages}
async function wordToPdf(file){const box=document.getElementById('docxRender'),C=await html2canvasLib(),J=await jsPDF();const pages=await renderDocxPages(file,box);let doc=null;for(let i=0;i<pages.length;i++){status(`Rendering Word page ${i+1} of ${pages.length}…`);const el=pages[i],canvas=await C(el,{scale:3,useCORS:true,backgroundColor:'#fff',logging:false,removeContainer:true,imageTimeout:30000});const wPt=canvas.width/3*72/96,hPt=canvas.height/3*72/96;if(!doc)doc=new J({unit:'pt',format:[wPt,hPt],orientation:wPt>=hPt?'landscape':'portrait',compress:true});else doc.addPage([wPt,hPt],wPt>=hPt?'landscape':'portrait');doc.addImage(canvas.toDataURL('image/jpeg',.98),'JPEG',0,0,wPt,hPt,undefined,'NONE')}if(!doc)throw Error('No document pages were rendered.');return doc.output('blob')}
async function pdfToPpt(file){const P=await pptxGen(),entries=await pdfPages(file,'png',2.5),ppt=new P();ppt.layout='LAYOUT_WIDE';ppt.author='USR Advisory & Consulting Services';ppt.subject='PDF to PowerPoint conversion';ppt.title='PDF to PowerPoint';const lib=await pdfjs(),pdf=await lib.getDocument({data:await file.arrayBuffer()}).promise;for(let i=0;i<entries.length;i++){const slide=ppt.addSlide();slide.background={color:'FFFFFF'};const bytes=await entries[i][1].arrayBuffer(),u='data:image/png;base64,'+btoa(String.fromCharCode(...new Uint8Array(bytes)));const page=await pdf.getPage(i+1),v=page.getViewport({scale:1}),ratio=v.width/v.height;let w=13.333,h=w/ratio;if(h>7.5){h=7.5;w=h*ratio}slide.addImage({data:u,x:(13.333-w)/2,y:(7.5-h)/2,w,h})}return await ppt.write({outputType:'blob'})}
async function pptToPdf(file){const mod=await pptxPreview();const init=mod.init||mod;const box=document.getElementById('pptxRender');if(!box)throw Error('Preview area is missing. Please refresh the page.');box.innerHTML='';box.style.width='1280px';box.style.minHeight='720px';box.style.background='#fff';const viewer=init(box,{width:1280,height:720});await viewer.preview(await file.arrayBuffer());await wait(500);const C=await html2canvasLib(),J=await jsPDF();let slides=[...box.querySelectorAll('[class*="slide"],canvas,svg')].filter(e=>e.offsetWidth&&e.offsetHeight);if(!slides.length)slides=[box];slides=slides.filter((e,i,a)=>a.indexOf(e)===i);let doc=null;for(let i=0;i<slides.length;i++){status(`Rendering PowerPoint slide ${i+1}…`);const el=slides[i],canvas=await C(el,{scale:2,useCORS:true,backgroundColor:'#fff',logging:false});const wPt=720,hPt=405;if(!doc)doc=new J({unit:'pt',format:[wPt,hPt],orientation:'landscape',compress:true});else doc.addPage([wPt,hPt],'landscape');doc.addImage(canvas.toDataURL('image/jpeg',.98),'JPEG',0,0,wPt,hPt,undefined,'NONE')}if(!doc)throw Error('No PowerPoint slides could be rendered. Please use a PPTX file.');return doc.output('blob')}
function bind(){setupFiles();const type=document.body.dataset.tool;if(!type)return;const input=$('input[type=file]');if(input)input.addEventListener('change',()=>{$('#fileNames').textContent=[...input.files].map(f=>f.name+' ('+bytesToMB(f.size)+')').join('\n');const n=$('#fileCount');if(n)n.textContent=`${input.files.length} file${input.files.length===1?'':'s'} selected`;});const go=$('#run');if(!go)return;go.addEventListener('click',async()=>{try{go.disabled=true;status('Working…');const files=[...input.files];if(!files.length)throw Error('Please choose at least one file.');
if(type==='jpg-pdf'||type==='images-pdf'){save(await imagePdf(files),type+'.pdf');status('Done. Your PDF is ready to download.');}
else if(type==='image-compressor'){const target=Number($('#target').value)*1024,maxW=Number($('#maxWidth').value)||2400,fmt=$('#format')?.value||'jpg',mime=fmt==='webp'?'image/webp':'image/jpeg',ext=fmt==='webp'?'webp':'jpg',results=[];for(const f of files){let q=.9,b=null;for(let i=0;i<14;i++){b=await canvasImage(f,maxW,q,mime);if(b.size<=target||q<=.2)break;q-=.05}results.push([f.name.replace(/\.[^.]+$/,'')+'.'+ext,b])}if(results.length===1)save(results[0][1],results[0][0]);else await blobZip(results,'compressed-images.zip');status(`Done. ${results.length} image${results.length===1?'':'s'} compressed.`);}
else if(type==='image-resizer'){const w=Number($('#width').value),h=Number($('#height').value);if(!w||!h)throw Error('Enter valid width and height.');const results=[];for(const f of files){const img=await imageLoad(f);let nw=w,nh=h;if($('#keep')?.checked){const s=Math.min(w/img.width,h/img.height);nw=Math.max(1,Math.round(img.width*s));nh=Math.max(1,Math.round(img.height*s))}const c=document.createElement('canvas');c.width=nw;c.height=nh;c.getContext('2d').drawImage(img,0,0,nw,nh);const b=await new Promise(r=>c.toBlob(r,'image/jpeg',.94));results.push([f.name.replace(/\.[^.]+$/,'')+'-resized.jpg',b])}if(results.length===1)save(results[0][1],results[0][0]);else await blobZip(results,'resized-images.zip');status(`Done. ${results.length} image${results.length===1?'':'s'} resized.`);}
else if(type==='pdf-jpg'||type==='pdf-png'){const format=type==='pdf-png'?'png':'jpg',scale=Number($('#quality')?.value||2),entries=await pdfPages(files[0],format,scale);if(entries.length===1)save(entries[0][1],files[0].name.replace(/\.[^.]+$/,'')+'-page-1.'+format);else await blobZip(entries,files[0].name.replace(/\.[^.]+$/,'')+'-'+format+'-pages.zip');status(`Done. Exported ${entries.length} page${entries.length===1?'':'s'} as ${format.toUpperCase()}.`);}
else if(type==='merge-pdf'){const L=await pdfLib(),out=await L.PDFDocument.create();for(const f of files){status(`Adding ${f.name}…`);const src=await L.PDFDocument.load(await f.arrayBuffer()),pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}save(new Blob([await out.save({useObjectStreams:true})],{type:'application/pdf'}),'merged.pdf');status(`Done. Merged ${files.length} PDF files in the selected order.`);}
else if(type==='compress-pdf'){const original=files[0],level=$('#compression')?.value||'recommended';status('Optimizing PDF structure and streams…');let result=await qpdfOptimize(await original.arrayBuffer(),level);if(!result)result=await safePdfOptimize(await original.arrayBuffer());if(result.size>=original.size){save(original,original.name.replace(/\.[^.]+$/,'')+'-optimized.pdf');status(`The original PDF was already smaller (${bytesToMB(original.size)}). The tool kept the original rather than producing a larger file.`)}else{save(result,original.name.replace(/\.[^.]+$/,'')+'-compressed.pdf');status(`Done. ${bytesToMB(original.size)} → ${bytesToMB(result.size)}. PDF structure and selectable content were preserved.`)}}
else if(type==='pdf-word'){const pages=await extractPdfText(files[0]);save(await docxBlobPages(pages),'pdf-to-word.docx');status(`Done. Created ${pages.length} Word page${pages.length===1?'':'s'} without an extra trailing page.`);}
else if(type==='word-pdf'){save(await wordToPdf(files[0]),files[0].name.replace(/\.[^.]+$/,'')+'.pdf');status('Done. High-resolution PDF created using the rendered Word page geometry.');}
else if(type==='pdf-ppt'){save(await pdfToPpt(files[0]),files[0].name.replace(/\.[^.]+$/,'')+'-to-powerpoint.pptx');status('Done. Each PDF page was placed as a high-resolution PowerPoint slide for visual fidelity.');}
else if(type==='ppt-pdf'){save(await pptToPdf(files[0]),files[0].name.replace(/\.[^.]+$/,'')+'.pdf');status('Done. PowerPoint slides were rendered at high resolution into a PDF.');}
}catch(e){console.error(e);status('Could not complete the conversion. '+(e.message||e));}finally{go.disabled=false}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
